version: '3.7'

services:
  node0:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node0
    hostname: tienda
    command: run --host 0.0.0.0 --port 8000
    entrypoint: flask
    environment:
      FLASK_APP: node_server.py
    ports:
      - 8000:8000
    volumes:
      - ./server:/code
    networks:
      - net
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node1
    hostname: tienda
    command: 
        flask run --host 0.0.0.0 --port 8000
    environment:
      FLASK_APP: node_server.py
    restart: always
    ports:
      - 8001:8000
    volumes:
      - ./server:/code
    depends_on:
      - node0
    networks:
      - net
  node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node2
    hostname: tienda
    command: 
        flask run --host 0.0.0.0 --port 8000 
    environment:
      FLASK_APP: node_server.py
    restart: always
    ports:
      - 8002:8000
    volumes:
      - ./server:/code
    depends_on:
      - node0
    networks:
      - net

networks:
  net:
